import assert from "node:assert/strict";
import test from "node:test";
import sharp from "sharp";
import { preserveOutsideMask } from "../lib/maskedEdit.js";

async function solidPng(width, height, rgba) {
  return sharp({ create: { width, height, channels: 4, background: rgba } })
    .png()
    .toBuffer();
}

test("masked edit restores protected source pixels and keeps editable output pixels", async () => {
  const original = await solidPng(2, 1, { r: 255, g: 0, b: 0, alpha: 1 });
  const generated = await solidPng(2, 1, { r: 0, g: 0, b: 255, alpha: 1 });
  const mask = await sharp(Buffer.from([
    255, 255, 255, 255,
    255, 255, 255, 0,
  ]), { raw: { width: 2, height: 1, channels: 4 } }).png().toBuffer();

  const output = await preserveOutsideMask({
    originalB64: original.toString("base64"),
    generatedB64: generated.toString("base64"),
    maskB64: mask.toString("base64"),
  });
  const { data, info } = await sharp(output).ensureAlpha().raw().toBuffer({ resolveWithObject: true });

  assert.deepEqual([info.width, info.height], [2, 1]);
  assert.deepEqual(Array.from(data.subarray(0, 4)), [255, 0, 0, 255]);
  assert.deepEqual(Array.from(data.subarray(4, 8)), [0, 0, 255, 255]);
});

test("unmasked edits pass through the generated bytes", async () => {
  const generated = Buffer.from("generated");
  const output = await preserveOutsideMask({
    originalB64: Buffer.from("original").toString("base64"),
    generatedB64: generated.toString("base64"),
    maskB64: null,
  });
  assert.deepEqual(output, generated);
});
